### ISSUE TITLE
create superuser fails

### ISSUE THREAD

**Issue by weidenba** [UKB-IT-Sec/NAC-Service-Portal#2]
```
python3 manage.py createsuperuser
Username: admin
Traceback (most recent call last):
  File "/home/weidenba/git/NAC-Service-Portal/src/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/weidenba/git/NAC-Service-Portal/src/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: nac_customuser
```

It seems that the database must be initalized before usage.

**Comment by weidenba** [comment]
The reason was that I deleted the whole src/nac/migrations/ folder instead of the single migration files. I modified the gitignore file and updated the README to execute makemigrations and migrate during the setup process.

**Comment by weidenba** [comment]
issue resolved
